In [1]:
from os import path
import os
import cv2
import face_recognition
from pickle import dump, load

In [2]:
path = "data/"
ThongTin = list(os.walk(path))

In [3]:
ThongTin

[('data/',
  ['Ngo Xuan Manh', 'Hoang Thi', 'Luong Tuan Anh', 'Pham Viet Anh'],
  []),
 ('data/Ngo Xuan Manh',
  [],
  ['8.jpg',
   '9.jpg',
   '14.jpg',
   '15.jpg',
   '17.jpg',
   '16.jpg',
   '12.jpg',
   '13.jpg',
   '11.jpg',
   '10.jpg',
   '18.jpg',
   '19.jpg',
   '4.jpg',
   '5.jpg',
   '7.jpg',
   '6.jpg',
   '2.jpg',
   '3.jpg',
   '1.jpg',
   '0.jpg']),
 ('data/Hoang Thi',
  [],
  ['8.jpg',
   '9.jpg',
   '14.jpg',
   '15.jpg',
   '17.jpg',
   '16.jpg',
   '12.jpg',
   '13.jpg',
   '11.jpg',
   '10.jpg',
   '21.jpg',
   '20.jpg',
   '22.jpg',
   '23.jpg',
   '26.jpg',
   '18.jpg',
   '24.jpg',
   '25.jpg',
   '19.jpg',
   '4.jpg',
   '5.jpg',
   '7.jpg',
   '6.jpg',
   '2.jpg',
   '3.jpg',
   '1.jpg',
   '0.jpg']),
 ('data/Luong Tuan Anh',
  [],
  ['8.jpg',
   '9.jpg',
   '14.jpg',
   '15.jpg',
   '17.jpg',
   '16.jpg',
   '12.jpg',
   '13.jpg',
   '11.jpg',
   '10.jpg',
   '21.jpg',
   '20.jpg',
   '22.jpg',
   '18.jpg',
   '19.jpg',
   '4.jpg',
   '5.jpg',
   '7.jpg',
  

In [4]:
ThongTinList = list(os.listdir(path))
ThongTinList

['Ngo Xuan Manh', 'Hoang Thi', 'Luong Tuan Anh', 'Pham Viet Anh']

In [5]:
len(ThongTin)

5

In [8]:
ThongTin[0][1][0]

'Ngo Xuan Manh'

In [12]:
ThongTin

[('data/',
  ['Ngo Xuan Manh', 'Hoang Thi', 'Luong Tuan Anh', 'Pham Viet Anh'],
  ['.DS_Store']),
 ('data/Ngo Xuan Manh',
  [],
  ['8.jpg',
   '9.jpg',
   '14.jpg',
   '15.jpg',
   '17.jpg',
   '16.jpg',
   '12.jpg',
   '13.jpg',
   '11.jpg',
   '10.jpg',
   '18.jpg',
   '19.jpg',
   '4.jpg',
   '5.jpg',
   '7.jpg',
   '6.jpg',
   '2.jpg',
   '3.jpg',
   '1.jpg',
   '0.jpg']),
 ('data/Hoang Thi',
  [],
  ['8.jpg',
   '9.jpg',
   '14.jpg',
   '15.jpg',
   '17.jpg',
   '16.jpg',
   '12.jpg',
   '13.jpg',
   '11.jpg',
   '10.jpg',
   '21.jpg',
   '20.jpg',
   '22.jpg',
   '23.jpg',
   '26.jpg',
   '18.jpg',
   '24.jpg',
   '25.jpg',
   '19.jpg',
   '4.jpg',
   '5.jpg',
   '7.jpg',
   '6.jpg',
   '2.jpg',
   '3.jpg',
   '1.jpg',
   '0.jpg']),
 ('data/Luong Tuan Anh',
  [],
  ['8.jpg',
   '9.jpg',
   '14.jpg',
   '15.jpg',
   '17.jpg',
   '16.jpg',
   '12.jpg',
   '13.jpg',
   '11.jpg',
   '10.jpg',
   '21.jpg',
   '20.jpg',
   '22.jpg',
   '18.jpg',
   '19.jpg',
   '4.jpg',
   '5.jpg',
   

In [3]:
known_face_encodings = []
known_face_names = []

In [4]:
for i in range(1,len(ThongTin),1):
    for infor in ThongTin[i][2]:
        name = ThongTin[0][1][i-1]
        image = infor
        full_path = path + "/" + name + "/"
        #print (full_path)
        img = face_recognition.load_image_file(full_path + image)
        #print(img)
        img_encoding = None
        try:
            img_encoding = face_recognition.face_encodings(img)[0]
        except:
            continue
        #print (img_encoding)
        known_face_names.append(name)
        known_face_encodings.append(img_encoding)

In [5]:
img_test = face_recognition.load_image_file('test.jpg')
img_test = cv2.resize(img_test,(240,240))

In [66]:
img_test

array([[[143, 158, 117],
        [146, 161, 120],
        [151, 166, 125],
        ...,
        [133, 147, 112],
        [133, 147, 112],
        [133, 147, 112]],

       [[142, 157, 116],
        [147, 162, 121],
        [152, 167, 126],
        ...,
        [134, 148, 113],
        [134, 148, 113],
        [134, 148, 113]],

       [[142, 157, 116],
        [147, 162, 121],
        [152, 167, 126],
        ...,
        [133, 147, 112],
        [133, 147, 112],
        [133, 147, 112]],

       ...,

       [[ 30,  45,  68],
        [ 35,  50,  73],
        [ 34,  50,  73],
        ...,
        [ 28,  45,  63],
        [ 29,  46,  64],
        [ 27,  44,  62]],

       [[ 23,  38,  61],
        [ 29,  44,  67],
        [ 28,  44,  67],
        ...,
        [ 31,  48,  66],
        [ 31,  48,  66],
        [ 28,  45,  63]],

       [[ 17,  32,  55],
        [ 22,  37,  60],
        [ 22,  38,  61],
        ...,
        [ 31,  48,  66],
        [ 30,  47,  65],
        [ 26,  43,  61]]

In [35]:
import numpy as np
encod_test = face_recognition.face_encodings(img_test)[0]
encod_test = np.asarray(encod_test)
encod_test.shape

(128,)

In [6]:
small_frame = cv2.resize(img_test, (0, 0), fx=0.5, fy=0.5)
rgb_img = small_frame[:, :, ::-1]

In [68]:
small_frame

array([[[145, 160, 119],
        [153, 168, 126],
        [151, 166, 123],
        ...,
        [134, 148, 113],
        [134, 148, 113],
        [134, 148, 113]],

       [[144, 160, 119],
        [152, 167, 125],
        [148, 163, 120],
        ...,
        [130, 144, 109],
        [132, 146, 111],
        [133, 147, 112]],

       [[145, 162, 120],
        [149, 166, 123],
        [150, 167, 123],
        ...,
        [133, 147, 112],
        [138, 152, 117],
        [142, 156, 121]],

       ...,

       [[ 28,  43,  64],
        [ 31,  48,  68],
        [ 33,  51,  71],
        ...,
        [  7,  23,  43],
        [ 10,  27,  46],
        [ 11,  28,  46]],

       [[ 33,  48,  71],
        [ 33,  49,  72],
        [ 29,  46,  68],
        ...,
        [ 12,  28,  48],
        [ 24,  41,  60],
        [ 25,  42,  60]],

       [[ 23,  38,  61],
        [ 24,  40,  63],
        [ 21,  38,  61],
        ...,
        [ 25,  41,  61],
        [ 31,  48,  67],
        [ 29,  46,  64]]

In [41]:
rgb_img

array([[[179, 191, 165],
        [177, 184, 160],
        [183, 185, 157],
        ...,
        [108, 110,  84],
        [100, 104,  85],
        [104, 108,  85]],

       [[180, 187, 163],
        [179, 186, 161],
        [185, 190, 166],
        ...,
        [104, 102,  75],
        [105, 105,  80],
        [105, 108,  73]],

       [[179, 190, 170],
        [175, 186, 165],
        [177, 185, 165],
        ...,
        [114, 105,  80],
        [109, 106,  72],
        [102, 101,  60]],

       ...,

       [[ 71,  52,  31],
        [ 66,  50,  29],
        [ 58,  46,  26],
        ...,
        [ 28,  13,   7],
        [ 33,  22,  16],
        [ 49,  38,  31]],

       [[ 63,  44,  25],
        [ 54,  40,  25],
        [ 54,  43,  36],
        ...,
        [ 35,  22,  12],
        [ 19,  15,   7],
        [ 31,  24,  19]],

       [[ 56,  37,  14],
        [ 52,  42,  26],
        [ 47,  41,  33],
        ...,
        [ 34,  24,   4],
        [ 10,  14,   2],
        [  6,  14,   5]]

In [7]:
face_locations = face_recognition.face_locations(rgb_img)
face_locations

[(46, 100, 108, 38)]

In [8]:
face_encodings = face_recognition.face_encodings(rgb_img, face_locations)
face_encodings
len(face_encodings)

1

In [16]:
face_encoding = face_encodings[0]
max = 1
name = "unknow"
for j in range(0, len(known_face_encodings), 1):
    chk = [known_face_encodings[j]]
    face_distances = face_recognition.face_distance(chk, face_encoding)
    print((face_distances))
    if (max > face_distances[0]):
        max = face_distances[0]
        name = known_face_names[j]
max = round(max,3)
        #print(max, name)

if max > 0.4:
    name = ""
y1, x2, y2, x1 = face_locations[0]
y1 = y1 *2
x2 = x2 *2
y2 = y2 *2
x1 = x1 *2
cv2.rectangle(img_test, (x1, y1), (x2, y2), (0, 255, 255), 2)
        #cv2.rectangle(img, (x1, y1 - 2), (x2, y2), (0, 0, 255), cv2.FILLED )
cv2.putText(img_test, str(max)+ name, (x1, y1), cv2.FONT_HERSHEY_DUPLEX, 0.6, (255, 0, 0), 1)
cv2.imwrite("dd.jpg",img_test)

[0.58728988]
[0.59316465]
[0.50711508]
[0.4913196]
[0.57381135]
[0.53626579]
[0.62431045]
[0.5925443]
[0.60857307]
[0.6052842]
[0.61868942]
[0.59619741]
[0.62831567]
[0.60246494]
[0.59625227]
[0.60113558]
[0.60041689]
[0.61568893]
[0.62759936]
[0.61147172]
[0.49207127]
[0.49085457]
[0.48837763]
[0.45751418]
[0.47285674]
[0.47618836]
[0.49181954]
[0.49965563]
[0.49284426]
[0.48761785]
[0.52669218]
[0.60189187]
[0.47498132]
[0.49681158]
[0.49407138]
[0.46575447]
[0.50153654]
[0.49401317]
[0.53756694]
[0.47762335]
[0.48536541]
[0.47871866]
[0.49282094]
[0.47746725]
[0.46637632]
[0.47082788]
[0.49074389]
[0.53282005]
[0.55862318]
[0.56047813]
[0.55966385]
[0.52805989]
[0.53675661]
[0.56427777]
[0.54275418]
[0.54799103]
[0.55568708]
[0.49281066]
[0.52284465]
[0.54925035]
[0.50398183]
[0.53751268]
[0.5263492]
[0.51362864]
[0.51726911]
[0.54527595]
[0.51511314]
[0.50330778]
[0.53263103]
[0.34480376]
[0.32401525]
[0.42722285]
[0.5373859]
[0.49673715]
[0.46609092]
[0.43260598]
[0.44765303]
[0.3

True

In [9]:
for i in range(0,len(face_encodings),1):
    face_encoding = face_encodings[i]

    max = 2
    name = "unknow"
    for j in range(0, len(known_face_encodings), 1):
        chk = [known_face_encodings[j]]
        face_distances = face_recognition.face_distance(chk, face_encoding)

        if (max > face_distances[0]):
            max = face_distances[0]
            name = known_face_names[j]
    max = round(max,2)
    print(max, name)

    if max > 0.3:
        name = ""
    y1, x2, y2, x1 = face_locations[i]
    y1 = y1 *2
    x2 = x2 *2
    y2 = y2 *2
    x1 = x1 *2
    cv2.rectangle(img_test, (x1, y1), (x2, y2), (0, 255, 255), 2)
    #cv2.rectangle(img, (x1, y1 - 2), (x2, y2), (0, 0, 255), cv2.FILLED )
    cv2.putText(img_test, str(max)+ name, (x1, y1), cv2.FONT_HERSHEY_DUPLEX, 0.6, (255, 0, 0), 1)

    cv2.imshow("Video",img_test)
    if cv2.waitKey(2)==ord('q'):
        break

0.32 Pham Viet Anh
